### ISSUE TITLE
1.8 update?

### ISSUE THREAD

**Issue by uoziod** [wcsiu/tdlib#1]
Any change having the latest tdlib please?

**Comment by wcsiu** [comment]
I am working on it. Dockerhub has removed the Automated Builds for free account. I am working on a github action script.

**Comment by wcsiu** [comment]
As a workaround for now, you can update the tdlib version in dockerfiles and build it locally.

**Comment by wcsiu** [comment]
1.8.0 should be ready with commit https://github.com/wcsiu/tdlib/commit/b14113d6e5fc9f75c00554999efedea3bcd339f8
I will close this ticket now.
